name: Build & Publish Debug APK

on:
  workflow_dispatch:

env:
  # The name of the main module repository
  main_project_module: "Hacker's Keyboard"
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

  #  - name: Update Gradle Wrapper
  #    uses: gradle-update/update-gradle-wrapper-action@v2
        
    - name: Make Gradle executable
      run: chmod +x ./gradlew

    - name: Restore gradle.properties
      shell: bash
      run: |
        mkdir -p ~/.gradle/
        echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
        echo ${GRADLE_PROPERTIES} > ~/.gradle/gradle.properties
      #  gradle wrapper --gradle-version 7.6.1 --info --stacktrace --debug
      
 #   - uses: gradle/gradle-build-action@v2
 #     with:
#      arguments: build
        
#    - name: Build with Gradle
#      run: ./gradlew build
    
      
    # Create APK Release
    - name: Build apk release project (APK) - ${{ env.main_project_module }} module
      run: ./gradlew assemble --scan
      env:
       GITHUB_TOKEN: ${{ secrets.toketoke }}
       APP_FOLDER: hackerskeyboard
       RELEASE_TITLE: New Build
