name: Build a Release APK

on:
  workflow_dispatch:

env:
  # The name of the main module repository
  main_project_module: "app"
      
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        env:
            ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
            TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
            mkdir "${TMP_KEYSTORE_FILE_PATH}"
            echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/replaceme_base64.txt
      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
   # Set up JDK 17
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

  #  - name: Update Gradle Wrapper
  #    uses: gradle-update/update-gradle-wrapper-action@v2
        
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Restore gradle.properties
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo ${GRADLE_PROPERTIES} > ~/.gradle/gradle.properties
        
      - name: Build with Gradle
        run: ./gradlew build --info -x lint
    
    # Create APK Release
      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        env:
         #GITHUB_TOKEN: ${{ secrets.toketoke }}
         APP_FOLDER: hackerskeyboard
         RELEASE_TITLE: New Build
         SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
         SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
         SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: list outputs
        run: ls ./app/; ls; ls ./app/build; ls; ls ./app/build/outputs/; ls; ls ./app/build/outputs/apk

   # Noted For Output [main_project_module]/build/outputs/apk/release/
      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - APK(s) release generated
          path: ./app/build/outputs/apk

